"""FM1 — the TUL-FM training arm: a flow-matching planner inside the live model.

Arc: ``.agents/notes/proposed/architecture/2026-08-28-tul-fm-arc.md``.
Config: ``morph/configs/tul_fm1.yaml``. Model wiring: ``MORPHTransformer._tul_fm_core``.

WHAT FM1 IS. Skeleton ``tul_a1`` — slots in the sequence, ``prefix_k`` coda positions per
slot, ``E_slot`` / ``W_prefix``, token-state dropout — but with ``n_core: 0``. The core
loop is GONE, and the :class:`~morph.model.fm_planner.FMPlanner` produces the slot states
instead. The slot state of slot ``i`` is a PLAN for span ``i+1``, generated by integrating
a conditional-flow-matching velocity field conditioned on the prelude states at positions
``<= e_i``.

THE ONE NON-NEGOTIABLE. The plan is ``detach()``ed before it is projected into the coda's
prefix positions. No gradient flows from the coda's cross-entropy into the planner, and
none flows through the Euler ladder into the backbone. That detach is the whole reason
this arm cannot develop the takeover disease: there is no BPTT through an iterated map,
because the iterated map is not in the CE graph at all. ``W_prefix`` still trains — it is
downstream of the detach — so the coda can learn to read the plan. See
``tests/test_tul_fm1.py::test_coda_ce_never_reaches_the_planner``.

THE THREE LOSS TERMS, and which parameters each one moves:

| term | gradient reaches |
|---|---|
| ``ce``     | backbone (prelude, coda, embeddings), ``E_slot``, ``E_mask``, ``W_prefix`` |
| ``fm``     | the FMPlanner ONLY — its context input is detached and its target is detached |
| ``sigreg`` | the backbone, through the pooled targets. This is the term that SHAPES them |

The split is deliberate and is the JEPA lesson: if the FM term could move the targets it
would take the cheapest available route and make them predictable rather than
informative. The targets are shaped by CE (they are prelude states of a language model)
and by SIGReg (isotropy), never by being easy to guess.
"""

from __future__ import annotations

import math
from dataclasses import dataclass

import torch
import torch.nn.functional as F
from torch import Tensor

from morph.model.fm_planner import FMPlannerConfig, SpanGeometry
from morph.model.sigreg import sigreg_epps_pulley
from morph.model.tul_layout import SlotLayout

__all__ = [
    "FMArmConfig",
    "fm_geometry",
    "fm_span_targets",
    "fm_sigreg_loss",
    "copy_gap_scores",
]


@dataclass
class FMArmConfig:
    """Construction-time settings for the FM1 arm. ``None`` on the model ⇒ no planner.

    Mirrors ``TULConfig``: this gates CONSTRUCTION. A model built without it has no
    planner parameters and every existing path is byte-identical.
    """

    # ── planner ──────────────────────────────────────────────────────────
    d_p: int = 512
    n_layers: int = 4
    n_heads: int = 8
    d_ff: int = 1408
    cond_dim: int = 256
    objective: str = "cfm"
    # Euler steps for plan GENERATION. Fixed inference constant — no loop-depth
    # variation in this arm (Wolfe veto, arc note).
    infer_steps: int = 6
    # Source scale of the CFM path, in TARGET space. See the warning in
    # `MORPHTransformer._build_fm` — with unit-L2 targets in d dims the matched value is
    # 1/sqrt(d), and 1.0 puts d times more variance in the source than in the target.
    source_std: float = 1.0
    t_embed_scale: float = 1.0
    dropout: float = 0.0
    # Shapes the planner is sized for. 0 -> derived from the model's max_seq_len, which
    # is an UPPER bound and therefore always safe but over-provisions the slot-index
    # embedding. `morph/training/fm_setup.py` passes the loader's exact values so the
    # shipped arm is sized to what it actually runs.
    max_slots: int = 0
    l_total: int = 0

    # ── loss weights ─────────────────────────────────────────────────────
    fm_weight: float = 1.0
    # `auto` divides the fm term by its analytic null floor so it starts near 1.0 and is
    # commensurate with a token CE of ~4-11 nats. `none` leaves it raw, which for cfm at
    # source_std 1.0 and d=1024 is a term of ~1025 that would drown the CE entirely.
    loss_scale: str = "auto"
    sigreg_lambda: float = 0.02
    sigreg_slices: int = 1024

    def __post_init__(self) -> None:
        if self.objective not in ("edm", "cfm"):
            raise ValueError(f"fm.objective must be 'edm' or 'cfm', got {self.objective!r}")
        if self.loss_scale not in ("auto", "none"):
            raise ValueError(f"fm.loss_scale must be 'auto' or 'none', got {self.loss_scale!r}")
        if self.infer_steps < 2:
            raise ValueError(f"fm.infer_steps must be >= 2, got {self.infer_steps}")
        for name in ("fm_weight", "sigreg_lambda"):
            if float(getattr(self, name)) < 0.0:
                raise ValueError(f"fm.{name} must be >= 0, got {getattr(self, name)}")
        if self.sigreg_slices < 1:
            raise ValueError(f"fm.sigreg_slices must be >= 1, got {self.sigreg_slices}")

    def planner_cfg(self, d_model: int, max_slots: int, l_total: int) -> FMPlannerConfig:
        max_slots = int(self.max_slots) or int(max_slots)
        l_total = int(self.l_total) or int(l_total)
        return FMPlannerConfig(
            objective=self.objective, d_ctx=d_model, d_target=d_model,
            d_p=self.d_p, n_layers=self.n_layers, n_heads=self.n_heads, d_ff=self.d_ff,
            cond_dim=self.cond_dim, max_slots=max_slots, max_ctx_len=l_total,
            source_std=self.source_std, t_embed_scale=self.t_embed_scale,
            dropout=self.dropout,
        )

    def manifest(self) -> dict:
        return {f"fm/{k}": v for k, v in self.__dict__.items()}


# ── geometry and targets, read off the SHIPPED layout ────────────────────────

def fm_geometry(layout: SlotLayout) -> SpanGeometry:
    """``SpanGeometry`` for the planner, derived from the TUL ``SlotLayout``.

    The layout already carries the span segmentation, so nothing here re-runs
    ``BoundaryRule`` — the planner's spans and the loader's spans are the same object by
    construction, not by two implementations agreeing.

    * ``slot_end[i] = slot_index[i] - 1`` — the LAST TOKEN of span ``i``. Slot ``i`` sits
      immediately after that token (``_tul_half_weights`` relies on the same fact), so
      this is the last position slot ``i`` may condition on. Its OWN slot positions are
      excluded, which costs nothing (they are a bag-mean of span ``i``, already visible)
      and removes a whole class of off-by-one leak.
    * the target span is span ``i+1``: token positions ``slot_index[i] + prefix_k`` through
      ``slot_index[i+1] - 1``.
    * a slot is a valid FM slot only when BOTH it and slot ``i+1`` are real, so the last
      real slot of every row is never an FM query — its span has no successor inside the
      row.
    """
    idx, val = layout.slot_index, layout.slot_valid
    B, S = idx.shape
    K = int(layout.prefix_k)
    L = layout.l_total

    nxt_valid = torch.zeros_like(val)
    nxt_valid[:, :-1] = val[:, 1:]
    valid = val & nxt_valid

    slot_end = (idx - 1).clamp_min(0)
    tgt_start = (idx + K).clamp(0, L - 1)
    nxt_idx = torch.zeros_like(idx)
    nxt_idx[:, :-1] = idx[:, 1:]
    tgt_end = (nxt_idx - 1).clamp(0, L - 1)

    slot_end = torch.where(valid, slot_end, torch.zeros_like(slot_end))
    tgt_start = torch.where(valid, tgt_start, torch.zeros_like(tgt_start))
    tgt_end = torch.where(valid, tgt_end, torch.zeros_like(tgt_end))

    n_valid = int(valid.sum())
    n_spans = int(val.sum())
    return SpanGeometry(
        slot_end=slot_end, tgt_start=tgt_start, tgt_end=tgt_end, valid=valid,
        n_spans_total=n_spans, n_slots_valid=n_valid,
        n_dropped_budget=0, seq_len=int(L),
    )


def fm_span_targets(h: Tensor, layout: SlotLayout, geom: SpanGeometry,
                    eps: float = 1e-8) -> Tensor:
    """``[B, S, d]`` UNIT-L2 pooled representation of each slot's NEXT span.

    Pooled from the layout's OWN ``bag_id`` map — the definition of "span ``i+1``'s token
    positions" — rather than from a contiguous index range. The two agree on every packed
    row (gated by a test against :func:`~morph.model.fm_planner.pool_targets`), but the
    bag map is what the loader actually used to build the slot inputs, so pooling from it
    cannot drift from the segmentation if the packer's padding ever changes.

    Unit L2 norm, not per-component std: ``SliceScaler`` is the scar (σ* 3.3, 77-98 % of
    training in the autoencoding regime). Invalid slots come back EXACTLY zero.

    GRADIENT: this is NOT detached. It is the path SIGReg uses to shape the targets, and
    the FM term detaches its own copy.
    """
    B, L, d = h.shape
    S = int(layout.max_slots)
    tok = (~layout.slot_mask)                                     # [B, L]
    bid = layout.bag_id.clamp(0, S)                               # S == the dump bin
    src = h * tok[..., None].to(h.dtype)
    acc = h.new_zeros(B, S + 1, d)
    acc.scatter_add_(1, bid[..., None].expand(B, L, d), src)
    cnt = h.new_zeros(B, S + 1)
    cnt.scatter_add_(1, bid, tok.to(h.dtype))
    span_mean = acc[:, :S] / cnt[:, :S].clamp_min(1.0)[..., None]  # [B, S, d]

    y = torch.zeros_like(span_mean)
    y[:, :-1] = span_mean[:, 1:]                                  # slot i -> span i+1
    y = y / y.norm(dim=-1, keepdim=True).clamp_min(eps)
    return y * geom.valid[..., None].to(y.dtype)


def fm_sigreg_loss(y: Tensor, valid: Tensor, num_slices: int = 1024) -> Tensor:
    """SIGReg (LeJEPA, arXiv 2511.08544) on the pooled targets, at the RIGHT scale.

    Calls the shipped :func:`~morph.model.sigreg.sigreg_epps_pulley` — MORPH already has
    one Epps-Pulley implementation and a second would drift from it.

    THE SCALE FIX, which is not optional. SIGReg tests each 1-D projection against
    ``N(0, 1)``, i.e. it asks for ``E‖z‖² = d``. The targets are UNIT L2 norm, so
    ``E‖y‖² = 1``. At ``d = 1024`` those two are incompatible by a factor of 1024, and
    running the statistic on ``y`` directly would report a large, irreducible loss whose
    gradient mostly pushes against the normaliser (which is scale-invariant and annihilates
    the radial component anyway).

    So the statistic runs on ``√d · y``. That is exactly the right question to ask of
    unit-norm vectors: by Poincaré's lemma a 1-D projection of the uniform distribution on
    the sphere of radius ``√d`` converges to ``N(0, 1)`` as ``d`` grows, and at
    ``d = 1024`` the approximation is excellent. "Be isotropic on the sphere" is
    achievable; "be N(0, I) while having unit norm" is not.
    ``tests/test_tul_fm1.py::test_sigreg_scale_fix_is_what_makes_the_statistic_achievable``
    measures both.
    """
    rows = y[valid]
    if rows.shape[0] < 2:
        return y.new_zeros(())
    d = rows.shape[-1]
    return sigreg_epps_pulley(rows * math.sqrt(d), num_slices=int(num_slices))


# ── the copy-gap instrument (P1's hardest-won number) ────────────────────────

def copy_gap_scores(zhat: Tensor, y: Tensor, valid: Tensor) -> dict:
    """Within-row retrieval of the planner AGAINST the zero-parameter copy baseline.

    P1 taught this the expensive way: the standalone planner reached within-row top-1
    0.0516 and "guess that the next span looks like the current one" — no parameters at
    all — scored 0.0678 on the same queries. Any retrieval number that is not compared to
    that baseline is unreadable.

    Both conditions are scored on the SAME query population and the SAME candidate set:

    * query slots are those with a previous slot in the row (the copy baseline needs one);
    * the candidate ``y_{i-1}`` is EXCLUDED, because it IS the copy baseline's guess and
      leaving it in would let the baseline retrieve itself;
    * the gold candidate is the slot's own target ``y_i``;
    * ties count against the query (``>=``), so a degenerate similarity scores worst.

    Ported from ``lab/experiments/results/2026-08-28-tulfm-p1/copy_baseline2.py`` and
    ``planner_excl.py`` — one vectorised callable instead of two scripts that could drift.
    """
    B, S, _d = y.shape
    dev = y.device
    k = F.normalize(y.float(), dim=-1)
    qz = F.normalize(zhat.float(), dim=-1)
    q_copy = torch.roll(k, 1, dims=1)                     # q_copy[:, i] = k[:, i-1]

    j = torch.arange(S, device=dev)
    prev_valid = torch.zeros_like(valid)
    prev_valid[:, 1:] = valid[:, :-1]
    query = valid & prev_valid                            # [B, S]
    if not bool(query.any()):
        raise ValueError("no slot has a previous slot in its row; copy_gap is undefined")

    is_prev = j[None, None, :] == (j[None, :, None] - 1)  # [1, S, S]
    allowed = valid[:, None, :] & (~is_prev)              # [B, S, S]
    gold_col = j[None, :, None].expand(B, S, 1)

    def _rank(q: Tensor) -> Tensor:
        sim = torch.einsum("bsd,bjd->bsj", q, k)
        gs = sim.gather(2, gold_col)
        return ((sim >= gs) & allowed).sum(-1)            # [B, S]

    r_plan = _rank(qz)[query].float()
    r_copy = _rank(q_copy)[query].float()
    n_cand = allowed.sum(-1)[query].float()
    out = {
        "n_queries": int(query.sum()),
        "n_candidates": float(n_cand.mean()),
        "chance": float((1.0 / n_cand.clamp_min(1.0)).mean()),
        "plan_top1": float((r_plan == 1).float().mean()),
        "plan_mrr": float((1.0 / r_plan.clamp_min(1.0)).mean()),
        "copy_top1": float((r_copy == 1).float().mean()),
        "copy_mrr": float((1.0 / r_copy.clamp_min(1.0)).mean()),
    }
    out["copy_gap"] = out["plan_top1"] - out["copy_top1"]
    out["copy_gap_mrr"] = out["plan_mrr"] - out["copy_mrr"]
    return out
