"""Autoregressive KV cache + incremental single-token decode for MORPH.

MORPH trains full-sequence and (before this module) generated by recomputing the WHOLE
forward every token (train.py:154). This module adds a real autoregressive decode: an
O(1)-per-token step that maintains a per-call-site KV cache for the looped CCA+CSA+HCA
attention, so generation is O(T·cache) instead of O(T²) recompute, and there is a concrete
KV-cache state to quantize for the KV-QAT ablation (Ai-notes/MORPH-Quant-Campaign/
KV_CACHE_DESIGN.md).

DESIGN (full rationale in KV_CACHE_DESIGN.md):
  * MORPH is fully causal ⇒ each position's state is fixed once decoded ⇒ cacheable.
  * The Parcae core is LOOPED (mean_depth iters at inference): core layer i at iter t has its
    own K/V/C_comp (h differs per iter) ⇒ the cache is keyed per ATTENTION CALL-SITE:
    3 prelude + n_core·mean_depth core + 3 coda sites.
  * Per-site rolling state: causal-conv history (k-1 inputs) + v_prev (1 input) folded into one
    `x_recent` buffer; window KV ring (last window-1 k,v); compressed C_comp blocks + an in-
    progress-block input buffer; CSA indexer keys K_I. Global: RoPE position + prev token id.
  * Every PER-POSITION op (embed, value-embed, bigram-inject, DiagonalInjection, ChannelInject,
    HC residual, RMSNorm, SwiGLU, LM head) is reused from the real modules on a length-1 tensor — only
    ATTENTION is reimplemented incrementally, mirroring the eager references EXACTLY
    (cca_prologue_reference / causal_conv_reference / _window_fallback / hca_/csa_
    attention_reference) with the one change being ABSOLUTE RoPE position.

This is a SEPARATE inference-only path: it does NOT add any `if cache` branch to the training
forward (repo law: no runtime flags in forward). Correctness is gated bit-tight on CPU against
the model's own eager-reference full forward (ignore/verify_kv_cache.py).
"""
from __future__ import annotations

from dataclasses import dataclass, field

import torch
import torch.nn.functional as F
from torch import Tensor

# Reference helpers — the SAME math the fused kernels fall back to. Mirroring these guarantees
# the decode reproduces the eager full-forward path.
from morph.kernels.triton.fused_cca_prologue import _rmsnorm, _rotate_half
from morph.kernels.triton.fused_cca_conv import causal_conv_reference
from morph.model.kv_quant import quant_dequant


# ─────────────────────────────────────────────────────────────────────────────
# Cache containers
# ─────────────────────────────────────────────────────────────────────────────


@dataclass
class AttnSiteCache:
    """Rolling state for one attention call-site (one (stage, layer, iter) triple)."""

    # last 2·(conv_kernel-1) attention inputs (zero-padded at start), [B, 2(k-1), d_model].
    # 2(k-1) because the conv is two stacked causal convs (composite RF = 2(k-1)+1). Feeds the
    # conv history AND v_prev (= W_v_prev(x_{P-1}) = proj of x_recent[:, -1]).
    x_recent: Tensor | None = None
    # window branch ring buffer: last (window_size-1) keys/values, [B, H, L, D].
    win_k: Tensor | None = None
    win_v: Tensor | None = None
    # compressed branch: completed blocks, [B, n_done, D]; comp_x = inputs of the in-progress
    # block window (last 2m for CSA two-stream / last m for HCA single-stream), [B, L, d_model].
    C_comp: Tensor | None = None
    comp_x: Tensor | None = None
    # CSA only: LightningIndexer keys for completed blocks, [B, n_done, d_indexer].
    K_I: Tensor | None = None
    # retention (GLA) running state for this call-site, [B, H, dk, dv] fp32. None → zero seed.
    # prelude/coda sites: pure causal token-axis accumulator (EXACT vs the full forward). core
    # sites: per-(layer,iter) accumulator; the cross-iteration carry is seeded at pos==0 from the
    # previous iteration's site state (the retention_carry approximation — see decode_step).
    ret_state: Tensor | None = None
    # KV-cache quantization (stamped from the parent MORPHKVCache at site() creation).
    # "off" → no quantization (bit-identical). Otherwise int{4,6,8} per-row absmax fake-quant
    # applied at the STORE site (win_k/win_v/C_comp/K_I), so reads are unchanged. See kv_quant.py.
    kv_quant: str = "off"
    kv_quant_group: int = 0


@dataclass
class MORPHKVCache:
    """Whole-model decode cache: one AttnSiteCache per attention call-site + global counters."""

    sites: dict[str, AttnSiteCache] = field(default_factory=dict)
    pos: int = 0                 # absolute position of the NEXT token to decode (0-indexed)
    prev_id: Tensor | None = None  # [B] previous token id (bigram key needs id_{t-1}); None→0
    # CSA top-k block-pool length (in TOKENS) for bit-exact selection parity with the clean CSA
    # forward: torch.topk tie-breaking among equal-scored visible blocks depends on n_blocks =
    # pool_len//csa_m, so set this to the deploy/eval seq_len (None → model's context_len). See
    # _csa_step.
    csa_pool_len: int | None = None
    # KV-cache quantization knob (PTQ, inference-only). "off" | "int8" | "int6" | "int4".
    # kv_quant_group = group size along the feature dim (0 → per-row). Applies to the cached
    # K/V tensors (win_k/win_v/C_comp/K_I); x_recent/comp_x stay bf16; top_idx stays exact.
    kv_quant: str = "off"
    kv_quant_group: int = 0

    def site(self, key: str) -> AttnSiteCache:
        c = self.sites.get(key)
        if c is None:
            c = AttnSiteCache(kv_quant=self.kv_quant, kv_quant_group=self.kv_quant_group)
            self.sites[key] = c
        return c


# ─────────────────────────────────────────────────────────────────────────────
# Incremental attention (the only cross-position op)
# ─────────────────────────────────────────────────────────────────────────────


def _q(sc: "AttnSiteCache", t: Tensor) -> Tensor:
    """Quantize a to-be-stored cache tensor if this site has KV-quant on (else identity).

    PTQ, inference-only: applied at the store site so the buffer holds the dequantized-from-int
    value and the verified read math is unchanged. Per-row absmax along the feature dim.
    """
    if sc.kv_quant == "off":
        return t
    return quant_dequant(t, int(sc.kv_quant[3:]), sc.kv_quant_group)


def _causal_conv_last_nocudnn(x_BCS: Tensor, w_dw: Tensor, w_gp: Tensor, k: int) -> Tensor:
    """Last-position output of the two stacked causal convs (depthwise → grouped), WITHOUT cudnn.

    Byte-equivalent to ``causal_conv_reference(x_BCS, w_dw, w_gp, k)[:, :, -1:]`` but built from
    ``unfold + einsum`` (plain matmul/reduction kernels) instead of ``F.conv1d``. WHY: at decode
    (S≈2k-1, single token) ``F.conv1d`` dispatches to cudnn, which on these tiny k=4 windows emits
    ~1300 NCHW<->NHWC layout-shuffle launches PER TOKEN — measured 38% of decode GPU time + the
    dominant launch-pressure source (ignore/profile_decode.py). The conv math is trivially small;
    cudnn's layout machinery is the whole cost. unfold+einsum avoids it entirely.

    w_dw: [C, 1, k] (depthwise, groups=C);  w_gp: [C_out, C_in//G, k] (grouped, G inferred).
    """
    p = k - 1
    B, C, S = x_BCS.shape
    # ── depthwise: y[b,c,s] = sum_j xp[b,c,s+j] * w_dw[c,0,j] ──
    xp = F.pad(x_BCS, (p, 0))                                  # [B, C, S+p]
    win = xp.unfold(2, k, 1)                                   # [B, C, S, k]
    y = torch.einsum("bcsk,ck->bcs", win, w_dw[:, 0, :].to(win.dtype))
    # ── grouped: G groups, Cg=C_in/G in-per-group, Co_g=C_out/G out-per-group ──
    Cg = w_gp.shape[1]
    G = C // Cg
    Co_g = w_gp.shape[0] // G
    yp = F.pad(y, (p, 0))                                      # [B, C, S+p]
    wing = yp.unfold(2, k, 1).reshape(B, G, Cg, S, k)         # group the INPUT channels
    wg = w_gp.reshape(G, Co_g, Cg, k).to(wing.dtype)          # group the OUTPUT channels
    yg = torch.einsum("bgisk,goik->bgos", wing, wg).reshape(B, w_gp.shape[0], S)
    return yg[:, :, -1:]                                       # [B, C_out, 1]


def _conv_last(x_recent: Tensor, x_t: Tensor, conv_dw, conv_gp) -> Tensor:
    """Causal conv output at the new position only.

    x_recent: [B, k-1, C] (zero-padded history), x_t: [B, 1, C]. Returns [B, 1, C].
    Mirrors _CCABase._causal_conv (causal_conv_reference): left-pad (k-1) zeros then two grouped
    conv1d. Feeding [history(k-1) + new(1)] and taking the last output column reproduces the
    full-sequence conv at this position exactly (the reference's own left-pad covers P<k-1).
    Uses the no-cudnn unfold+einsum form (see _causal_conv_last_nocudnn) — decode-critical.
    """
    xr = torch.cat([x_recent, x_t], dim=1)              # [B, S, C]
    y_last = _causal_conv_last_nocudnn(
        xr.transpose(1, 2),                             # [B, C, S]
        conv_dw.weight.to(xr.dtype), conv_gp.weight.to(xr.dtype),
        conv_dw.kernel_size[0],
    )                                                   # [B, C, 1]
    return y_last.transpose(1, 2)                        # [B, 1, C]


def _prologue_one(cca, x_recent: Tensor, x_t: Tensor, pos: int):
    """CCA prologue for ONE new position. Returns q,k,v each [B, H, 1, D] (GQA-expanded).

    Byte-faithful to cca_prologue_reference, specialised to S=1 with RoPE at ABSOLUTE `pos`.
    """
    H, Hkv, D, n_rep = cca.n_heads, cca.n_kv_heads, cca.d_head, cca.n_rep
    B = x_t.shape[0]

    q_lat = cca.W_down_q(x_t)                            # [B,1,H*D]
    k_lat = cca.W_down_k(x_t)                            # [B,1,Hkv*D]
    q_conv = _conv_last(cca.W_down_q(x_recent), q_lat, cca.conv_q_dw, cca.conv_q_gp)
    k_conv = _conv_last(cca.W_down_k(x_recent), k_lat, cca.conv_k_dw, cca.conv_k_gp)

    v_curr = cca.W_v_curr(x_t)                           # [B,1,Hkv*D/?] (value half)
    v_prev = cca.W_v_prev(x_recent[:, -1:])              # proj of x_{pos-1} (zero at pos 0)

    # QK-mean coupling (cca_prologue_reference lines 661-668)
    q_pre = q_lat.reshape(B, 1, H, D)
    k_pre = k_lat.reshape(B, 1, Hkv, D)
    k_pre_exp = k_pre.repeat_interleave(n_rep, dim=2)
    qk_mean_q = (q_pre + k_pre_exp) * 0.5
    qk_mean_k = qk_mean_q.reshape(B, 1, Hkv, n_rep, D).mean(dim=3)

    q = (q_conv.reshape(B, 1, H, D) + qk_mean_q).transpose(1, 2)    # [B,H,1,D]
    k = (k_conv.reshape(B, 1, Hkv, D) + qk_mean_k).transpose(1, 2)  # [B,Hkv,1,D]

    q = _rmsnorm(q, cca.q_norm.weight, cca.q_norm.eps)
    k = _rmsnorm(k, cca.k_norm.weight, cca.k_norm.eps)
    k = k * torch.exp(cca.temp).view(1, Hkv, 1, 1)

    # RoPE at ABSOLUTE position `pos` (the one deviation from the full-seq reference, which
    # slices cos/sin to [:S]).
    cos = cca.rope.cos_cached[:, :, pos:pos + 1].reshape(-1, D).to(q.dtype)   # [1,D]
    sin = cca.rope.sin_cached[:, :, pos:pos + 1].reshape(-1, D).to(q.dtype)
    cb = cos.view(1, 1, 1, D)
    sb = sin.view(1, 1, 1, D)
    q = q * cb + _rotate_half(q) * sb
    k = k * cb + _rotate_half(k) * sb

    k = k.repeat_interleave(n_rep, dim=1)               # [B,H,1,D]
    v = torch.cat([v_curr, v_prev], dim=-1).reshape(B, 1, Hkv, D).transpose(1, 2)
    v = v.repeat_interleave(n_rep, dim=1)               # [B,H,1,D]
    return q, k, v


def _window_step(q_t: Tensor, win_k: Tensor | None, win_v: Tensor | None,
                 scale: float) -> Tensor:
    """Window attention of the new query against the cached window (XSA: self not in buffer).

    q_t: [B,H,1,D]; win_k/win_v: [B,H,L,D] = the last (window-1) keys (positions [P-w+1..P-1]),
    all causal/in-window/non-self by construction ⇒ plain softmax, no mask. Empty buffer → 0
    (mirrors the all-masked row at P=0). Equivalent to _window_fallback restricted to the valid
    key set.
    """
    if win_k is None or win_k.shape[2] == 0:
        return torch.zeros_like(q_t)
    scores = torch.einsum("bhqd,bhkd->bhqk", q_t, win_k).float() * scale   # [B,H,1,L]
    w = F.softmax(scores, dim=-1).to(q_t.dtype)
    return torch.einsum("bhqk,bhkd->bhqd", w, win_v)                       # [B,H,1,D]


def _hca_step(q_t: Tensor, C_comp: Tensor | None, sink_logits: Tensor,
              scale: float) -> Tensor:
    """HCA dense compressed attention over the (already causally-visible) C_comp + sink.

    Mirrors hca_attention_reference with the causal-block mask implicit (C_comp only holds
    blocks emitted before this step = exactly block_end < pos). Empty → 0 (early-query guard).
    """
    B, H, _, D = q_t.shape
    if C_comp is None or C_comp.shape[1] == 0:
        return torch.zeros_like(q_t)
    scores = torch.einsum("bhqd,bnd->bhqn", q_t, C_comp).float() * scale    # [B,H,1,n]
    sink = sink_logits.view(1, H, 1, 1).expand(B, -1, 1, 1).float()
    scores_aug = torch.cat([scores, sink], dim=-1)
    w = F.softmax(scores_aug, dim=-1).to(q_t.dtype)[..., :-1]               # drop sink col
    return torch.einsum("bhqn,bnd->bhqd", w, C_comp)


def _csa_step(q_t: Tensor, C_comp: Tensor | None, K_I: Tensor | None,
              x_t: Tensor, indexer, top_k: int, sink_logits: Tensor,
              scale: float, n_pool: int) -> Tensor:
    """CSA top-k compressed attention, bit-identical to the (clean) _CCACSAAttention.forward.

    The model's CSA does `scores.masked_fill(~causal, -inf).topk(min(top_k, n_blocks))` over ALL
    n_blocks = seq_len/m blocks: future (causally-invalid) blocks are -inf so a visible block is
    always preferred (clean causal selection). BUT `torch.topk` tie-breaking among equal-scored
    VISIBLE blocks (common: indexer relu clamps negatives to 0) is sensitive to the total array
    length — so the SET of selected tied blocks still depends on n_blocks. To reproduce the
    forward exactly we pad the n_vis visible scores with (n_pool - n_vis) **-inf** entries (the
    masked future blocks) before top-k, where `n_pool = seq_len/m` (the model's block count).
    Selected phantoms (idx >= n_vis, only when n_vis < top_k) are masked out of the attention.
    """
    B, H, _, D = q_t.shape
    if C_comp is None or C_comp.shape[1] == 0:
        return torch.zeros_like(q_t)
    n_vis = C_comp.shape[1]
    # indexer raw score (q_I · K_I), relu (matches LightningIndexer for the visible blocks).
    q_I = indexer.W_IQ(x_t)                                                 # [B,1,d_I]
    raw = torch.bmm(q_I, K_I.transpose(1, 2)).float()                      # [B,1,n_vis]
    scores_I = F.relu(raw)

    pool = max(n_vis, n_pool)
    if pool > n_vis:                                                        # phantom future = -inf
        scores_I = torch.cat(
            [scores_I, scores_I.new_full((B, 1, pool - n_vis), float("-inf"))], dim=-1)
    tk = min(top_k, pool)
    _, top_idx = scores_I.topk(tk, dim=-1)                                 # [B,1,tk]

    valid = top_idx < n_vis                                                # [B,1,tk]
    safe_idx = top_idx.clamp(max=n_vis - 1)
    batch_idx = torch.arange(B, device=q_t.device)[:, None, None]
    C_sel = C_comp[batch_idx, safe_idx]                                    # [B,1,tk,D]
    attn = torch.einsum("bhqd,bqtd->bhqt", q_t, C_sel).float() * scale     # [B,H,1,tk]
    attn = attn.masked_fill(~valid.unsqueeze(1), float("-inf"))           # phantom slots → -inf
    sink = sink_logits.view(1, H, 1, 1).expand(B, -1, 1, 1).float()
    scores_aug = torch.cat([attn, sink], dim=-1)
    w = F.softmax(scores_aug, dim=-1).to(q_t.dtype)[..., :-1]
    w = w.masked_fill(~valid.unsqueeze(1), 0.0)
    return torch.einsum("bhqt,bqtd->bhqd", w, C_sel)


def _maybe_emit_block(impl, sc: AttnSiteCache, x_t: Tensor, pos: int, is_csa: bool):
    """Append x_t to the in-progress-block buffer and, when a block completes at this position
    ((pos+1) % m == 0), pool it via the real compressor and append to C_comp (+ K_I for CSA).

    Emission happens AFTER this step's attention (caller order), so the new block is visible only
    to FUTURE queries — matching the `block_end < query_pos` reference mask.
    """
    m = impl.compress_ratio
    # rolling input buffer: keep last 2m (CSA needs prev block for the two-stream) / m (HCA).
    keep = 2 * m if is_csa else m
    sc.comp_x = x_t if sc.comp_x is None else torch.cat([sc.comp_x, x_t], dim=1)[:, -keep:]

    if (pos + 1) % m != 0:
        return
    # a block just completed (block index j = pos // m, covering tokens [pos-m+1 .. pos]).
    if is_csa:
        # two-stream block j fuses stream-A(curr m) + stream-B(prev m). Pass [prev,curr] (≤2m)
        # and take the LAST output block; first block (only m available) → B-stream is -inf.
        win = sc.comp_x                              # [B, m or 2m, d_model]
        blk = impl.comp_norm(impl.compressor(win))[:, -1:]          # [B,1,D]
        ki = impl.indexer.compressor(win[:, -m:])[:, -1:]          # [B,1,d_I] single-stream
        # KV-quant: K_I quantization perturbs the CSA top-k SELECTION (a real, measured effect).
        ki = _q(sc, ki)
        sc.K_I = ki if sc.K_I is None else torch.cat([sc.K_I, ki], dim=1)
    else:
        win = sc.comp_x[:, -m:]
        blk = impl.comp_norm(impl.compressor(win))[:, -1:]          # [B,1,D]
    # KV-quant: compressed blocks serve as BOTH key and value in the compressed branch.
    blk = _q(sc, blk)
    sc.C_comp = blk if sc.C_comp is None else torch.cat([sc.C_comp, blk], dim=1)


def _attn_step(impl, x_t: Tensor, sc: AttnSiteCache, pos: int,
               csa_pool: int | None = None) -> Tensor:
    """Incremental CCA attention for one new token. impl = _CCACSAAttention | _CCAHCAAttention.

    x_t: [B,1,d_model] (the norm_attn output). Returns [B,1,d_model]. Reproduces
    _CCA{CSA,HCA}Attention.forward for the single new query, reading/updating the site cache.
    csa_pool: CSA top-k block-pool size (= eval/deploy seq_len // csa_m) for bit-exact selection
    parity with the trained forward; None → clean causal top-k over visible blocks.
    """
    cca = impl.cca
    B, _, _ = x_t.shape
    H, D = cca.n_heads, cca.d_head
    # The CCA conv is TWO stacked causal convs (depthwise → grouped), so the composite
    # receptive field at position P spans 2·(k-1)+1 inputs. We must carry 2·(k-1) history (not
    # k-1): conv_gp at P reads conv_dw[P-(k-1)..P], each of which reads inputs back to P-2(k-1).
    k_hist = 2 * (cca.conv_q_dw.kernel_size[0] - 1)
    scale = D ** -0.5
    is_csa = hasattr(impl, "indexer")

    if sc.x_recent is None:
        sc.x_recent = x_t.new_zeros(B, k_hist, x_t.shape[-1])

    q_t, k_t, v_t = _prologue_one(cca, sc.x_recent, x_t, pos)

    out_win = _window_step(q_t, sc.win_k, sc.win_v, scale)
    if is_csa:
        out_comp = _csa_step(q_t, sc.C_comp, sc.K_I, x_t, impl.indexer,
                             impl.top_k, cca.sink_logits, scale, csa_pool)
    else:
        out_comp = _hca_step(q_t, sc.C_comp, cca.sink_logits, scale)

    # update window ring (append this position's k,v; keep last window-1) AFTER attention (XSA).
    # KV-quant: the STORED k,v are quantized (the live query q_t is never quantized).
    w_keep = cca.window_size - 1
    k_st, v_st = _q(sc, k_t), _q(sc, v_t)
    sc.win_k = k_st if sc.win_k is None else torch.cat([sc.win_k, k_st], dim=2)[:, :, -w_keep:]
    sc.win_v = v_st if sc.win_v is None else torch.cat([sc.win_v, v_st], dim=2)[:, :, -w_keep:]
    # emit a compressed block if one completes at this position (visible to future queries only).
    _maybe_emit_block(impl, sc, x_t, pos, is_csa)
    # roll the conv/v_prev history.
    sc.x_recent = torch.cat([sc.x_recent, x_t], dim=1)[:, -k_hist:]

    # gate-combine-up (byte-faithful to _CCABase._gate_combine_up, S=1).
    g = torch.sigmoid(cca.gate(x_t)).reshape(B, 1, H, 2).permute(0, 2, 1, 3)   # [B,H,1,2]
    combined = g[..., 0:1] * out_comp + g[..., 1:2] * out_win                  # [B,H,1,D]
    x_res = cca.W_down_q(x_t).reshape(B, 1, H, D).transpose(1, 2)
    out = combined + cca.alpha * x_res
    return cca.W_up(out.transpose(1, 2).reshape(B, 1, cca.latent_q_dim))


# ─────────────────────────────────────────────────────────────────────────────
# Block + full-model decode step
# ─────────────────────────────────────────────────────────────────────────────


def _block_step(block, h: Tensor, sc: AttnSiteCache, pos: int, iter_idx: int,
                ret_state: Tensor | None, csa_pool: int | None = None):
    """MORPHBlock.forward for ONE token — byte-faithful to mhc.MORPHBlock.forward, swapping only
    the cross-position op (full attention → cached incremental _attn_step).

    h is the HC carrier ``[B,1,n,C]``. The block's ``mrr_attn``/``mrr_mlp`` modules
    (HyperConnectionResidual — ``mrr_*`` is a retained legacy attribute name, kept for
    checkpoint compatibility) manage the stream carrier; the sublayer fns operate on the
    single-stream ``[B,1,C]`` the residual reduces to, with no special-casing.

    Mirrors mhc.MORPHBlock.forward's sublayer closures exactly:
      * _attn_fn: incremental attention + (if present) the gated GLA retention branch
        ``a + sigmoid(ret_gate)·gla(norm_ret(x), state)``, returning the new GLA state.
      * _mlp_fn:  ``drop(mlp(norm_mlp(x), iter_idx=iter_idx))`` — iter_idx threads to the ReMoE
        router (prelude/coda → 0, core → loop iteration t), matching the training forward.

    Returns (h_new, new_ret_state). new_ret_state is None unless this block carries retention.
    """
    impl = block.attention._impl
    new_ret: dict = {}

    def _attn_fn(x: Tensor) -> Tensor:           # x: [B,1,C] single-stream (HC-reduced)
        a = _attn_step(impl, block.norm_attn(x), sc, pos, csa_pool)
        if block.retention is not None:
            g_out, s_out = block.retention(block.norm_ret(x), initial_state=ret_state)
            new_ret["state"] = s_out
            a = a + torch.sigmoid(block.ret_gate).to(a.dtype) * g_out
        return block.drop(a)

    def _mlp_fn(x: Tensor) -> Tensor:
        return block.drop(block.mlp(block.norm_mlp(x), iter_idx=iter_idx))

    h = block.mrr_attn(h, _attn_fn)
    h = block.mrr_mlp(h, _mlp_fn)
    return h, new_ret.get("state")


@torch.no_grad()
def decode_step(model, token_ids: Tensor, cache: MORPHKVCache) -> Tensor:
    """Decode ONE new token (all batch elements at the same absolute position cache.pos).

    token_ids: [B] or [B,1] int. Returns next-token logits [B, vocab]. Mutates `cache`.
    Mirrors MORPHTransformer._forward_single's eval per-position pipeline at S=1:
      HC stream expand → prelude → core×mean_depth → coda → HC stream reduce → LM head.
    Uses the CURRENT injection API (_build_injection_term + _apply_injection) and the REAL
    block forward (HC residual + ReMoE router + GLA retention), swapping only attention for the
    cached incremental step.

    Retention (#230): prelude/coda GLA branches are decoded EXACTLY (pure causal token-axis
    accumulator per site). The CORE retention layer's cross-iteration carry (retention_carry) is
    non-causal in the full forward (it carries iter t's END-OF-SEQUENCE state — including future
    tokens — into iter t+1), so it has no bit-exact O(1) form. We approximate it causally: each
    (core layer, iter t) site keeps its own token-axis running state, seeded at pos==0 from the
    previous iteration's freshly-updated state. Error is bounded by the (tiny ~1.3%) retention
    gate; quantified against the O(T^2) full-recompute generation in ignore/verify_kv_cache.py.
    """
    cfg = model.cfg
    ids = token_ids.view(-1, 1)                                   # [B,1]
    B = ids.shape[0]
    pos = cache.pos
    np_, nc = cfg.n_prelude, cfg.n_core
    T = cfg.mean_depth
    # CSA top-k block-pool = pool_len // csa_m (see _csa_step).
    pool_len = cache.csa_pool_len if cache.csa_pool_len is not None else cfg.context_len
    csa_pool = int(pool_len) // int(cfg.csa_compress_ratio)
    ret_layers = set(model._retention_layers) if model._core_has_retention else set()

    # bigram needs id_{t-1}: feed [prev_id, id] and take the new token's row.
    prev = cache.prev_id if cache.prev_id is not None else torch.zeros_like(ids[:, 0])
    pair = torch.stack([prev, ids[:, 0]], dim=1)                  # [B,2]
    bigram_emb = model.embed.get_bigram(pair)[:, -1:]            # [B,1,bg_dim]

    x = model.embed_drop(model.embed(ids))                        # [B,1,d_model]
    x0 = x                                                        # single-stream skip signal

    # ── HC stream expansion (mirror _forward_single: x → [B,1,n,C]) ──
    if model._is_hc:
        x = x.unsqueeze(2).expand(B, 1, model._n_streams, x.shape[-1]).contiguous()

    # ── Prelude ──
    for i, layer in enumerate(model.prelude):
        term = model._build_injection_term(
            i, model.x0_injects[i].precompute(x0), ids, bigram_emb, x.dtype)
        x = model._apply_injection(x, term)
        sc = cache.site(f"prelude.{i}")
        x, new_ret = _block_step(layer, x, sc, pos, 0, sc.ret_state, csa_pool)
        if new_ret is not None:
            sc.ret_state = new_ret

    # ── Core loop ──
    e = model.input_norm(x)
    h = e
    x0_core_terms = [model.x0_injects[np_ + i].precompute(x0) for i in range(nc)]
    for t in range(T):
        h = model.injection(h, e)
        for i, layer in enumerate(model.core):
            gi = np_ + i
            term = model._build_injection_term(gi, x0_core_terms[i], ids, bigram_emb, h.dtype)
            h = model._apply_injection(h, term)
            sc = cache.site(f"core.{i}.{t}")
            ret_in = None
            if i in ret_layers:
                # cross-iteration carry seed at pos==0: from the previous iteration's site,
                # freshly updated earlier in THIS decode_step (causal approximation).
                if sc.ret_state is None and t > 0:
                    sc.ret_state = cache.site(f"core.{i}.{t - 1}").ret_state
                ret_in = sc.ret_state
            h, new_ret = _block_step(layer, h, sc, pos, t, ret_in, csa_pool)
            if i in ret_layers and new_ret is not None:
                sc.ret_state = new_ret
    x = h

    # ── Coda ──
    for i, layer in enumerate(model.coda):
        gi = np_ + nc + i
        term = model._build_injection_term(
            gi, model.x0_injects[gi].precompute(x0), ids, bigram_emb, x.dtype)
        x = model._apply_injection(x, term)
        sc = cache.site(f"coda.{i}")
        x, new_ret = _block_step(layer, x, sc, pos, 0, sc.ret_state, csa_pool)
        if new_ret is not None:
            sc.ret_state = new_ret

    # ── HC stream reduction (mean readout) before the LM head ──
    if model._is_hc:
        x = x.mean(dim=2)

    # ── LM head ──
    x = model.lm_mixer(x)
    x = model.final_norm(x)
    logits = model.embed.attend(x)                                # [B,1,vocab]

    cache.prev_id = ids[:, 0]
    cache.pos = pos + 1
    return logits[:, -1, :]


@torch.no_grad()
def prefill(model, input_ids: Tensor, cache: MORPHKVCache | None = None) -> tuple[Tensor, MORPHKVCache]:
    """Prime the cache on a prompt by stepping token-by-token. Returns (last-token logits, cache).

    Correctness-first (reuses the verified single-step path). A fused chunked prefill is a later
    optimisation; the per-token loop is bit-identical to it.
    """
    if cache is None:
        cache = MORPHKVCache()
    ids = input_ids
    logits = None
    for t in range(ids.shape[1]):
        logits = decode_step(model, ids[:, t], cache)
    return logits, cache
